apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-autoimageupdate
  namespace: test-flux
spec:
  selector:
    matchLabels:
      app: busybox-autoimageupdate
  template:
    metadata:
      labels:
        app: busybox-autoimageupdate
    spec:
      containers:
        - name: pbusybox-autoimageupdate-c
          image: ghcr.io/dorong95/busybox:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9898
              protocol: TCP
