apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-autoimageupdate
  namespace: test-flux
spec:
  selector:
    matchLabels:
      app: busybox-autoimageupdate
  template:
    metadata:
      labels:
        app: busybox-autoimageupdate
    spec:
      imagePullSecrets:
        - name: registry-credentials
      containers:
        - name: pbusybox-autoimageupdate-c
          image: ghcr.io/dorong95/busybox:1.2.5 # {"$imagepolicy": "flux-system:image-busybox"}
          command: ["sleep", "3600"]
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9898
              protocol: TCP
